# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FanBase' do

	pod 'STTwitter'
	pod 'AFNetworking', '~> 3.0'
	pod 'Firebase', '>= 2.5.1'

end

