# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'FanBase' do

	pod 'STTwitter'
	pod 'AFNetworking', '~> 3.0'
	pod 'AFOAuth2Manager', :git => 'https://github.com/AFNetworking/AFOAuth2Manager.git', :branch => '3_0_0_branch'
	pod 'Firebase', '>= 2.5.1'

end

